#ifndef STM32_PRINTER_V2_X_USERCONFIG_H
#define STM32_PRINTER_V2_X_USERCONFIG_H


/* LED */
#define LED_RCC_CLK_ENABLE_FUN __HAL_RCC_GPIOB_CLK_ENABLE
#define LED_PIN_PORT GPIOB
#define LED_PIN GPIO_PIN_0

#define USE_LOW_LEVEL_DRIVE 1

#if USE_LOW_LEVEL_DRIVE
#define ON GPIO_PIN_RESET
#define OFF GPIO_PIN_SET
#elif
#define ON GPIO_PIN_SET
#define OFF GPIO_PIN_RESET
#endif

#define LED_INITIAL_STATE OFF


#endif//STM32_PRINTER_V2_X_USERCONFIG_H
